### ISSUE TITLE
ImportError: libavutil.so.55: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by jujuran2** [radimspetlik/hr-cnn#7]
sorry ,excuse me , I have the same problem with the new updated project.
[INFO]Performing experiments on ecg-fitness database, protocol test.
[INFO]Loading model 08-05-2018_23-04-07-384974_arch=FaceHRNet09V4ELURGB_lr=1E-05_batch-size=300_fine_tuning_extractor_val_mae_best.
[WARNING]Was not able to load state_dictionary, trying to add/remove "module."...
[INFO]Model 08-05-2018_23-04-07-384974_arch=FaceHRNet09V4ELURGB_lr=1E-05_batch-size=300_fine_tuning_extractor_val_mae_best loaded.
Traceback (most recent call last):
File "/home/a203/Music/hr-cnn-master/test-evaluation.py", line 128, in 
perform_experiments(dataset, 'test')
File "/home/a203/Music/hr-cnn-master/test-evaluation.py", line 89, in perform_experiments
faces_dir) + ' --outdir ' + str(pulse_dir) + ' --batch-size ' + str(batch_size))
File "/home/a203/Music/hr-cnn-master/cmp/nrppg/experiments/extract_pulse_cnn.py", line 185, in main
import bob.db.ecg_fitness
File "/home/a203/Music/hr-cnn-master/bob/db/ecg_fitness/init.py", line 7, in 
from models import *
File "/home/a203/Music/hr-cnn-master/bob/db/ecg_fitness/models.py", line 15, in 
import utils
File "/home/a203/Music/hr-cnn-master/bob/db/ecg_fitness/utils.py", line 8, in 
import bob.io.video
File "/home/a203/Music/hr-cnn-master/bob/io/video/init.py", line 4, in 
from ._library import *
ImportError: libavutil.so.55: cannot open shared object file: No such file or directory

After I install with sudo apt-get install libav-tools , the ImportError: libavutil.so.55: cannot open shared object file: No such file or directory still exists.

**Comment by amberhappy** [comment]
There is something wrong with ffmpeg, run 'ffmpeg' in cmd, you can see some libs an there version number, make sure that the version of libavutil is ....55.
And two ways to solve the problem: 1.run conda env update --file environment.yml, not manually install 
2. install ffmpeg which support libavutil 55 directly .
I suggest the first way.

**Comment by jujuran2** [comment]
> ffmpeg有问题，在cmd中运行'ffmpeg'，你可以看到一些libs的版本号，确保libavutil的版本是.... 55。
> 以及解决问题的两种方法：1.run conda env update --file environment.yml，不要手动安装
> 2.直接支持libavutil 55的安装ffmpeg。
> 我建议第一种方式。

Thank you for answer me. I am a begineer.  I run this code in linux(ubuntu16) envrionment python2.7 , First, I want to ask how to run "ffmpeg"  in cmd to see version . Before, I tried to run conda env update --file environment.yml, but some problems have been encountered 
"Collecting package metadata: done
Solving environment: failed
ResolvePackageNotFound: 
  - bob.blitz=2.0.16".

**Comment by jujuran2** [comment]
> There is something wrong with ffmpeg, run 'ffmpeg' in cmd, you can see some libs an there version number, make sure that the version of libavutil is ....55.
> And two ways to solve the problem: 1.run conda env update --file environment.yml, not manually install
> 2. install ffmpeg which support libavutil 55 directly .
> I suggest the first way.

Thank you for answer me. I am a begineer. I run this code in linux(ubuntu16) envrionment python2.7 , First, I want to ask how to run "ffmpeg" in cmd to see version . Before, I tried to run conda env update --file environment.yml, but some problems have been encountered
"Collecting package metadata: done
Solving environment: failed
ResolvePackageNotFound:
bob.blitz=2.0.16".

**Comment by radimspetlik** [comment]
@jujuran2 to install bob package, please follow the instructions on their site... [installation](https://www.idiap.ch/software/bob/docs/bob/docs/stable/bob/bob/doc/install.html)

**Comment by bitcarm** [comment]
Trying to run the code on a Windows machine, I have the same issue with bob.blitz package... Like you suggested, I looked up in bob installation instructions and found "bob does not work in Windows". Is there a way to fix this issue and run the net regardless of the operating system?

**Comment by radimspetlik** [comment]
Hi,

bob is not required for running the network, it is required for
running the experiments presented in the paper...

On 25/09/2020, bitcarm <notifications@github.com> wrote:
> Trying to run the code on a Windows machine, I have the same issue with
> bob.blitz package... Like you suggested, I looked up in bob installation
> instructions and found "bob does not work in Windows". Is there a way to fix
> this issue and run the net regardless of the operating system?
>
> --
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/radimspetlik/hr-cnn/issues/7#issuecomment-698978640


-- 
Radim V. Špetlík
Gagarinova 791 / 3, Liberec 7, 460 07

GSM: 00420 775 277 208
Skype ID: radim.spetlik

O.A.D.G.

**Comment by bitcarm** [comment]
Thanks, Radim.

I'm a beginner and I was simply following the installation steps. So, I assume I can skip the bob issue and pass the data to the net or is there a preprocessing step needed?

**Comment by radimspetlik** [comment]
Check the code for running the network, please :)
